# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-26 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='广告描述'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='广告标题'),
        ),
    ]
