# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-26 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20181226_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=50, verbose_name='广告标题'),
        ),
    ]
