# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-27 04:50
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20181226_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容详情'),
        ),
    ]
